const projects = [
    {
        id: 0,
        title: "C++ Chess",
        gitUrl: "https://github.com/Calvinbullock/Chess",
        startDate: "May 18, 2022",
        lastUpdate: "Aug 20, 2022",
        desc: "This is one of my first programs, I made it back in  May 18, 2022",
        longDesc: "",
        heroImage: "./images/Chess-Game-Play.png",
        altText: "Game running",
        youtubeUrl: null,
        tags: ['c++', 'games', 'oop', 'terminal', 'PersinalProject'],
    },
    {
        id: 1,
        title: "NewLife Game",
        gitUrl: "https://github.com/Calvinbullock/new-life",
        startDate: "Sep 2, 2023",
        lastUpdate: "--",
        desc: "This is a adventure tile game. It is built using c++ and the SFML library.",
        longDesc: "\tI got the idea from the object orietaed class I took in my 4th semester. My final was building a simple turnbased game. I took this idea and originally planned to exspand on it. But as I started I decided to make it a whole new thing. This game is what came from that.<br><br>\tI am still working on this project when I can find time between classwork.",
        heroImage: "./images/New-Life-Game-Play.png",
        altText: "Game running",
        youtubeUrl: "https://www.youtube.com/watch?v=TKum7AfY2Do",
        tags: ['c++', 'games', 'oop', 'gui', 'PersinalProject'],
    },
    {
        id: 2,
        title: "Go-Lang BattleShip",
        gitUrl: "https://github.com/Calvinbullock/battleship",
        startDate: "Feb 12, 2024",
        lastUpdate: "May 19, 2024",
        desc: "A Battleship game that runs in the terminal.",
        longDesc: "This is a game that I built while learing go. It is a little rough but I had a lot of fun makeing it. <br><br>I hope to oneday get a single player mode buit for it, that would use a computer player to play the user.",
        heroImage: "./images/go-lang-battleship.png",
        altText: "Game running",
        youtubeUrl: "https://youtu.be/NTacSqyuzAA",
        tags: ['go-lang', 'games', 'tui', 'PersinalProject'],
    },
    {
        id: 3,
        title: "PyServer",
        gitUrl: "https://github.com/Calvinbullock/PyServer",
        startDate: "eb 4, 2024",
        lastUpdate: "",
        desc: "This is a frontend I built for my dads apache webserver that we use to serve files. It uses the apache cgi library.",
        longDesc: "This takes the basic apache file table display and adds a dark mode, and search functionality.",
        heroImage: "",
        altText: "",
        youtubeUrl: "",
        tags: ["website", "python", "PersinalProject", "cgi-library", "apache"],
    },
]

export default projects 
