const projects = [
    {
        id: 0,
        title: "C++ Chess",
        gitUrl: "https://github.com/Calvinbullock/Chess",
        startDate: "May 18, 2022",
        lastUpdate: "Aug 20, 2022",
        desc: "This is one of my first programs, I made it back in  May 18, 2022",
        longDesc: "This was one of my earliest programs I heard that the university I wanted to go to uses c++ so I wanted to learn it and get ahead. It ended up being one of the best and most use-full projects I ever did. I learned so much and have used what I learned here in all my programming since.",
        heroImage: "./images/Chess-Game-Play.png",
        altText: "Game running",
        youtubeUrl: null,
        tags: ['c++', 'games', 'oop', 'terminal', 'PersinalProject'],
    },
    {
        id: 1,
        title: "NewLife Game",
        gitUrl: "https://github.com/Calvinbullock/new-life",
        startDate: "Sep 2, 2023",
        lastUpdate: "--",
        desc: "This is a adventure tile game. It is built using c++ and the SFML library.",
        longDesc: "\tI got the idea from the object oriented class I took in my 4th semester. My final was building a simple turn based game. I took this idea and originally planned to expand on it. But as I started I decided to make it a whole new thing. This game is what came from that.<br><br>\tI am still working on this project when I can find time between classwork.",
        heroImage: "./images/New-Life-Game-Play.png",
        altText: "Game running",
        youtubeUrl: "https://www.youtube.com/watch?v=TKum7AfY2Do",
        tags: ['c++', 'games', 'oop', 'gui', 'PersinalProject'],
    },
    {
        id: 2,
        title: "Go-Lang BattleShip",
        gitUrl: "https://github.com/Calvinbullock/battleship",
        startDate: "Feb 12, 2024",
        lastUpdate: "May 19, 2024",
        desc: "A Battleship game that runs in the terminal.",
        longDesc: "This is a game that I built while learing go. It is a little rough but I had a lot of fun making it. <br><br>I hope to one day get a single player mode built for it, that would use a computer player to play the user.",
        heroImage: "./images/go-lang-battleship.png",
        altText: "Game running",
        youtubeUrl: "https://youtu.be/NTacSqyuzAA",
        tags: ['go-lang', 'games', 'tui', 'PersinalProject'],
    },
    {
        id: 3,
        title: "PyServer",
        gitUrl: "https://github.com/Calvinbullock/PyServer",
        startDate: "eb 4, 2024",
        lastUpdate: "Oct 12, 2022",
        desc: "This is a frontend I built for my dads apache webserver that we use to serve files. It uses the apache cgi library.",
        longDesc: "This takes the basic Apache file table display and adds a dark mode, and search functionality. It is a quick and simple build but it adds the functionality that I felt my dads home server was lacking. And most of my siblings have moved over to this rather then the default version as both are still accessible. Even my dad has been quite happy with it. But he also has mentioned that it needs to have more dynamic \"sort by\" options. So I need to add that.<br><br>Sadly I don't have any pictures or video as the server is at my dads.",
        heroImage: "",
        altText: "",
        youtubeUrl: null,
        tags: ["website", "python", "PersinalProject", "cgi-library", "apache"],
    },
]

export default projects 
